# Site settings
title: "Marc Wright"
description: 'ramblings on music and code'
url: 'https://marcwright.github.io/marcwright-jekyll'
baseurl: '/marcwright-jekyll/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Marc Wright'
  email: marc.wright@gmail.com
  twitter_username: m4rcw
  # facebook_username: marcwright
  github_username:  marcwright
  linkedin_username:  marcwright1

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
